Add bake support (#11)
resolves #6

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -15,16 +15,36 @@ permissions:
   packages: write # publish to GitHub Packages
 
 jobs:
-  test:
-    name: Test
+  linting-tests:
+    name: Linting Tests
     runs-on: ubuntu-24.04
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v3
+        uses: actions/checkout@v5
 
-      - uses: actions/setup-go@v5
+      - uses: jdx/mise-action@v3
         with:
-          go-version-file: 'go.mod'
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Run go lint
+        run: golangci-lint run --fix
+
+      - name: Run go vet
+        run: go vet ./...
+
+      - name: Run go fmt
+        run: go fmt ./...
+
+  unit-tests:
+    name: Unit Tests
+    runs-on: ubuntu-24.04
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v5
+
+      - uses: jdx/mise-action@v3
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
 
       # docker builds and dockerhub access required by tests
       - name: Set up QEMU
@@ -39,8 +59,8 @@ jobs:
           username: hytromo
           password: ${{ secrets.DOCKER_PAT }}
       
-      - name: Run tests
-        run: go test ./... -coverprofile=coverage.txt
+      - name: Run unit tests
+        run: mise run tests:unit
 
       - name: Upload results to Codecov
         uses: codecov/codecov-action@v5
@@ -52,22 +72,103 @@ jobs:
     runs-on: ubuntu-24.04
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v3
+        uses: actions/checkout@v5
 
-      - uses: actions/setup-go@v5
+      - uses: jdx/mise-action@v3
         with:
-          go-version-file: 'go.mod'
+          github_token: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Go build
         run: |
-            CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o mimosa ./cmd/mimosa/*
+            CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o mimosa .
 
+        # make sure that the tests below can get and use the built binary
       - uses: actions/upload-artifact@v4
         with:
           name: mimosa
           path: mimosa
 
-  e2e:
+  integration-tests:
+    needs: build
+    runs-on: ubuntu-24.04
+    timeout-minutes: 20
+    name: "Integration tests with dockerignore=${{ matrix.dockerignore }}, location=${{ matrix.bakefile_location }}, dockerfile=${{ matrix.dockerfile_type }}"
+    strategy:
+      fail-fast: false
+      matrix:
+        dockerignore: [single, multiple, none]
+        bakefile_location: [root, subdir]
+        dockerfile_type: [single, multiple]
+    steps:
+      - uses: actions/checkout@v5
+
+      - uses: jdx/mise-action@v3
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Install Python dependencies
+        run: mise run init:python
+
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v3
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+
+      - name: Download the mimosa binary
+        uses: actions/download-artifact@v5
+        with:
+          name: mimosa
+          path: /usr/local/bin
+
+      - name: Make mimosa executable
+        run: chmod +x /usr/local/bin/mimosa
+
+      - name: "Run integration tests"
+        working-directory: tests-integration
+        env:
+          dockerignore: ${{ matrix.dockerignore }}
+          bakefile_location: ${{ matrix.bakefile_location }}
+          dockerfile_type: ${{ matrix.dockerfile_type }}
+        run: mise run tests:integration
+
+      - name: Upload test summary artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: test-summary-${{ matrix.dockerignore }}-${{ matrix.bakefile_location }}-${{ matrix.dockerfile_type }}
+          path: tests-integration/integration_tests_summary.json
+
+  integration-tests-summarizer:
+    needs: integration-tests
+    runs-on: ubuntu-24.04
+    name: "Summarize test results"
+    steps:
+      - name: Download all test summary artifacts
+        uses: actions/download-artifact@v4
+        with:
+          path: test-summaries
+
+      - name: Calculate and print totals
+        run: |
+          total_tests=$(find test-summaries -name "integration_tests_summary.json" -exec cat {} + | jq -s '[.[] | .total_tests_run] | add')
+
+          SUMMARY_CONTENT=$(cat <<EOF
+          ### 📋 Integration Tests Summary
+          | Metric           | Count |
+          |------------------|-------|
+          | **Total Tests Run** | \`$total_tests\` |
+          EOF
+          )
+
+          echo "$SUMMARY_CONTENT" >> $GITHUB_STEP_SUMMARY
+
+          # fail anyway if total tests run is less than 100 - as a fail safe
+          if [ "$total_tests" -lt 100 ]; then
+            echo "Error: Total tests run ($total_tests) is less than expected - something is fishy."
+            exit 1
+          fi
+
+  e2e-tests:
     name: E2E Tests
     runs-on: ubuntu-24.04
     needs: build
@@ -77,9 +178,9 @@ jobs:
         registry: [DockerHub, "GCP GAR", "AWS ECR", "GitHub Packages"]
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v3
+        uses: actions/checkout@v5
 
-      - name: Download artifact
+      - name: Download the mimosa binary
         uses: actions/download-artifact@v5
         with:
           name: mimosa
@@ -185,18 +286,18 @@ jobs:
 
   release:
     name: Release
-    needs: [build, test, e2e]
+    needs: [build, unit-tests, e2e-tests, integration-tests, linting-tests]
     permissions:
       contents: write # write release
-    if: startsWith(github.ref, 'refs/tags/v')
+    if: startsWith(github.ref, 'refs/tags/v') # only on version tags
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
-        uses: actions/checkout@v4
+        uses: actions/checkout@v5
 
-      - uses: actions/setup-go@v5
+      - uses: jdx/mise-action@v3
         with:
-          go-version-file: 'go.mod'
+          github_token: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Run GoReleaser
         uses: goreleaser/goreleaser-action@v6
